liberaforms/views/invite.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2021 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""


from flask import Blueprint, redirect, request
from flask import current_app, flash, g, url_for, jsonify
from flask_babel import gettext as _
import flask_login
from liberaforms.models.invite import Invite
from liberaforms.models.formuser import FormUser
from liberaforms.utils import auth

invite_bp = Blueprint('invite_bp', __name__)


@invite_bp.route('/invite/preview', methods=['POST'])
@auth.enabled_editor_required__json
def invite_preview():
    if request.method == 'POST' and 'language' in request.form:
        if request.form["language"] in g.site.custom_languages:
            if "text" in request.form and request.form["text"]:
                preview = Invite.get_preview(request.form["text"])
                text = Invite.prepare_message(request.form["text"], replace_vars=False)
            else:
                default_msg = Invite.default_message(request.form["language"])
                preview = Invite.get_preview(default_msg)
                text = ""
            return jsonify(text=text, preview=preview), 200
    return jsonify(preview="Not found"), 406

liberaforms/views/site.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2020 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

import os
import json
import mimetypes
import markdown
import markupsafe
from feedgen.feed import FeedGenerator
from sqlalchemy.orm.attributes import flag_modified
from flask import g, request, render_template, redirect, Response
from flask import Blueprint, current_app, url_for
from flask import session, flash, jsonify
from jinja2 import Template
from flask_babel import gettext as _
from flask_babel import force_locale
import flask_login

from liberaforms.models.site import Site
from liberaforms.models.invite import Invite
from liberaforms.models.user import User
from liberaforms.models.form import Form
from liberaforms.models.consent import Consent
from liberaforms.models.schemas.consent import ConsentSchema
from liberaforms.models.formconsent import FormConsent
from liberaforms.domain.user import UserDomain
from liberaforms.utils import utils
from liberaforms.utils import auth
from liberaforms.utils import sanitizers
from liberaforms.utils import tokens
from liberaforms.utils import html_parser
from liberaforms.utils.chart_data import get_site_statistics
from liberaforms.utils.dispatcher import Dispatcher
from liberaforms.utils import wtf
from liberaforms.utils import i18n
from liberaforms.utils.inline_help import InlineHelp

# from pprint import pprint

site_bp = Blueprint('site_bp', __name__,
                    template_folder='../templates/site')


@site_bp.route('/site/recover-password', methods=['GET', 'POST'])
def recover_password():
    if flask_login.current_user.is_authenticated:
        flask_login.logout_user()
    wtform = wtf.GetEmail()
    if wtform.validate_on_submit():
        user = User.find(email=wtform.email.data, blocked=False)
        if user:
            user.save_token()
            Dispatcher().send_account_recovery(user)
        elif wtform.email.data == current_app.config['ROOT_USER']:
            # auto invite root user
            invite = Invite(email=wtform.email.data,
                            message="New root user",
                            token=tokens.create_token(),
                            role='admin',
                            invited_by_id=None)
            invite.save()
            return redirect(url_for('user_bp.create_new_user',
                                    invite=invite.token['token']))
        flash(_("We may have sent you an email"), 'info')
        return redirect(url_for('main_bp.index'))
    return render_template('user/recover-password.html', wtform=wtform)


@site_bp.route('/site/new-user-form', methods=['GET'])
@auth.enabled_admin_required
def new_user_form_preview():
    consents = ConsentSchema(
                many=True,
                only=('id', 'label', 'text', 'field_name', 'checkbox_label', 'required')
                ).dump(g.site.get_registration_consents())
    consent_library = ConsentSchema(many=True).dump(g.site.consents)
    return render_template('user/new-user.html',
                           wtform=wtf.NewUser(),
                           consents=consents,
                           consent_library=consent_library,
                           preview_only=True)


@site_bp.route('/site/new-user-form/enable-consent', methods=['POST'])
@auth.enabled_admin_required__json
def new_user_form_enable_consent():
    if not ('consent_id' in request.form and 'enable' in request.form):
        return jsonify("Not Acceptable"), 406
    consent_id = json.loads(request.form['consent_id'])
    enable = utils.str2bool(request.form['enable'])
    consent = Consent.find(id=consent_id, site_id=g.site.id)
    if not consent:
        return jsonify("Not found"), 404
    if consent.id in g.site.registration_consent and not enable:
        g.site.registration_consent.remove(consent.id)
    elif consent.id not in g.site.registration_consent and enable:
        g.site.registration_consent.append(consent.id)
    g.site.save()
    consents = ConsentSchema(
                many=True,
                only=('id', 'label', 'text', 'field_name', 'checkbox_label', 'required')
                ).dump(g.site.get_registration_consents())
    return jsonify(enabled_consents=consents), 200


# ## Site settings

@site_bp.route('/site/look-and-feel', methods=['GET'])
@auth.enabled_admin_required
def look_and_feel():
    wtcolorform = wtf.ChangeTheme()
    wtcolorform.primary_color.data = g.site.theme["primary_color"]
    wtcolorform.font_color.data = g.site.theme['navbar']['font_color']
    return render_template('site/look-and-feel.html',
                           wtcolorform=wtcolorform,
                           human_readable_bytes=utils.human_readable_bytes,
                           site=g.site)


@site_bp.route('/site/change-name', methods=['POST'])
@auth.enabled_admin_required
def change_name():
    if request.method == 'POST' and 'sitename' in request.form:
        name = sanitizers.remove_html_tags(request.form['sitename'])
        if name:
            g.site.name = name
            g.site.save()
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/change-icon', methods=['POST'])
@auth.enabled_admin_required
def change_icon():
    if not request.files['file']:
        flash(_("Required file is missing"), 'warning')
        return redirect(url_for('site_bp.look_and_feel'))
    file = request.files['file']
    if "image/" in file.content_type:
        try:
            g.site.change_favicon(file)
            flash(_("Logo changed OK. Refresh with <F5>"), 'success')
        except Exception as error:
            current_app.logger.error(error)
    else:
        flash(_("An image file is required"), 'warning')
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/reset-icon', methods=['GET'])
@auth.enabled_admin_required
def reset_icon():
    if g.site.reset_favicon():
        flash(_("Logo reset OK. Refresh with <F5>"), 'success')
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/change-theme', methods=['POST'])
@auth.enabled_admin_required
def change_theme():
    wtform = wtf.ChangeTheme()
    if wtform.validate_on_submit():
        g.site.theme["primary_color"] = wtform.primary_color.data
        g.site.theme['navbar']['font_color'] = wtform.font_color.data
        g.site.save()
        flash(_("Colors updated OK"), 'success')
    return redirect(url_for('site_bp.look_and_feel'))


@site_bp.route('/site/new-user-language', methods=['GET', 'POST'])
@auth.enabled_admin_required
def set_new_user_language():
    if request.method == 'POST':
        if 'language' in request.form and \
          request.form['language'] in current_app.config['LANGUAGES']:
            g.site.newuser_language = request.form['language']
            g.site.save()
            flash(_("Language updated OK"), 'success')
            return redirect(url_for('admin_bp.admin_panel'))
    return render_template('new-user-language.html',
                           current_language=g.site.newuser_language)


@site_bp.route('/site/mimetypes', methods=['GET', 'POST'])
@auth.enabled_admin_required
def edit_mimetypes():
    wtform = wtf.FileExtensions()
    if wtform.validate_on_submit():
        mimetypes.init()
        updated_mimetypes = {"extensions": [], "mimetypes": []}
        extensions = wtform.extensions.data.splitlines()
        for extension in extensions:
            if not extension:
                continue
            mime_type = mimetypes.types_map[f".{extension}"]
            if extension not in updated_mimetypes["extensions"]:
                updated_mimetypes["extensions"].append(extension)
                updated_mimetypes["mimetypes"].append(mime_type)
        g.site.mimetypes = updated_mimetypes
        g.site.save()
        flash(_("Enabled file extensions updated OK"), 'success')
    if request.method == 'GET':
        wtform.extensions.data = '\n'.join(g.site.mimetypes['extensions'])
    return render_template('edit-mimetypes.html', wtform=wtform)


@site_bp.route('/site/toggle-invitation-only', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_invitation_only():
    return jsonify(invite=g.site.toggle_invitation_only())


@site_bp.route('/site/toggle-newuser-uploads-default', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_newuser_uploads_default():
    return jsonify(uploads=g.site.toggle_newuser_uploads_default())

# ## i18n texts


@site_bp.route('/site/custom-translations', methods=['GET'])
@auth.enabled_admin_required
def custom_languages():
    lang_codes = os.path.join(current_app.config['ASSETS_DIR'], 'language_codes.json')
    with open(lang_codes, 'r', encoding="utf-8") as all_languages:
        languages = json.load(all_languages)
    return render_template('site/custom-translations.html',
                           custom_languages=i18n.get_custom_languages(),
                           all_languages=languages)


@site_bp.route('/site/add-custom-language', methods=['POST'])
@auth.enabled_admin_required__json
def add_custom_language():
    if not ("lang_code" in request.form and request.form["lang_code"]):
        return jsonify("Not acceptable"), 406
    lang_code = request.form["lang_code"]
    if lang_code in g.site.custom_languages:
        return jsonify("Not acceptable"), 406
    lang_codes = os.path.join(current_app.config['ASSETS_DIR'], 'language_codes.json')
    with open(lang_codes, 'r', encoding="utf-8") as all_languages:
        languages = json.load(all_languages)
    selected_lang = [d for d in languages if d['value'] == lang_code]
    if not selected_lang:
        return jsonify("Not acceptable"), 406
    g.site.custom_languages.append(lang_code)
    g.site.save()
    enabled = [d for d in languages if d['value'] in g.site.custom_languages]
    return jsonify(custom_languages=i18n.sort_languages(enabled)), 200


@site_bp.route('/site/remove-custom-language', methods=['POST'])

liberaforms/templates/site/custom-translations.html
{% extends "base-backend.html" %}
{% block content %}

<!-- site_custom_languages_page -->

<script src="/static/vendor/bs5-autocomplete/autocomplete.js"></script>

<div class="ds-narrow-container">

  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">
      <a href="{{url_for('admin_bp.admin_panel')}}" arial-label="return"><i data-feather="arrow-left"></i></a>
      <h1>{{ _("Custom translations") }}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <p class="mb-0">
        {{ _("Define the languages used to translate custom texts.") }}
        <a href="#" onclick="toggleInlineHelp('site_customlanguages.j2.md')">{{ _("Learn more") }}</a>
      </p>
    </div>
  </div>

  <div class="grid mt-3 ds-wrapper-white">
    <div class="g-col-12">
      <ul id="enabled_language_list" class="ds-list-group"></ul>
    </div>
  </div>

  <div class="grid mt-4 ds-wrapper-white">
    <div class="g-col-12">
      <label class="form-label">{{_("Add a language")}}</label>
      <div class="input-group mb-4">
        <input type="text" class="form-control" id="new-language" placeholder="{{_('Start typing...')}}" autocomplete="off">
      </div>
    </div>
  </div>

</div>

<script>
const inline_help_file_name = "site_customlanguages.j2.md";
var custom_languages = {{custom_languages|tojson}};
var default_language = "{{g.site.language}}"
$(function() {
  updateDisplay();
  $('#enabled_language_list').on("click", ".language-radio", function(){
    setDefaultLanguage($(this).val())
  });
});
const field = document.getElementById('new-language');
const ac = new Autocomplete(field, {
    data: {{all_languages|tojson}},
    label: "name",
    maximumItems: 5,
    threshold: 1,
    onSelectItem: ({label, value}) => {
      $.ajax({
          url : "{{url_for('site_bp.add_custom_language')}}",
          type: "POST",
          data : {
            lang_code: value,
          },
          dataType: "json",
          beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
          },
          success: function(data, textStatus, jqXHR)
          {
            custom_languages = data.custom_languages
            updateDisplay();
            $("#new-language").val("")
          }
      });
    }
});
function removeLang(lang_code) {
  $.ajax({
      url : "{{url_for('site_bp.remove_custom_language')}}",
      type: "POST",
      data : {
        lang_code: lang_code,
      },
      dataType: "json",
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      },
      success: function(data, textStatus, jqXHR)
      {
        custom_languages = data.custom_languages
        updateDisplay();
        $("#new-language").val("")
      }
  });
}
function setDefaultLanguage(lang_code) {
  $.ajax({
      url : "{{url_for('site_bp.set_custom_language')}}",
      type: "POST",
      data : {
        lang_code: lang_code,
      },
      dataType: "json",
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      },
      success: function(data, textStatus, jqXHR)
      {
        custom_languages = data.custom_languages
        default_language = data.default_language
        updateDisplay();
      }
  });
}
function updateDisplay() {
  $('#enabled_language_list').html("")
  custom_languages.forEach(function(language) {
    var template = lang_template.replace(/%lang_code%/g, language.value)
                                .replace(/%lang_name%/g, language.name);
    let is_default = language.value == default_language
    template = template.replace(/%disabled%/, is_default ? "disabled":"")
    template = template.replace(/%checked%/, is_default ? "checked":"")
    template = template.replace(/%default%/, is_default ? "({{_('default')}})":"")
    $('#enabled_language_list').append(template);
  })
}
const lang_template = `
<li>
  <span>
    <input id="%lang_code%-lang" type="radio" %checked% class="language-radio" value="%lang_code%" arial-label="{{_('Default language')}} %lang_name%" />
    <label for="%lang_code%-lang">%lang_name% %default%
  </span>
  <span>
    <button %disabled% class="btn btn-sm btn-danger" onclick="removeLang('%lang_code%')">{{_("Remove")}}</button>
  </span>
</li>
`
</script>

{% endblock %}

liberaforms/templates/site/invitation-template.html
{% extends "base-backend.html" %}
{% block content %}

<!-- edit_invitation_text_page -->

<div class="ds-narrow-container">

  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">
      <a href="{{ url_for('admin_bp.admin_panel', goto='custom-texts')}}" arial-label="return"><i data-feather="arrow-left"></i></a>
      <h1>{{ _("Invitation template") }}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <p class="mb-0">{{ _("This template can be edited when inviting a new user.") }}</p>
    </div>
  </div>

  <form name="inviteText" method="post" class="mt-3">
    <div class="grid ds-wrapper-white">
      <div class="g-col-12">
        {{ wtform.csrf_token }}
        {% if g.site.custom_languages|length > 1 %}
        <div class="mb-4">
          {{ wtform.language.label(for="language", class_="form-label") }}
          {{ wtform.language(id="language", class_="form-select", onchange="changeLanguage()") }}
        </div>
        {% else %}
          <input id="language" type="hidden" name="language" value="{{g.site.language}}" />
        {% endif %}
        <div class="">
        {{ wtform.text.label(for="template-text", class_="form-label") }}
        {{ wtform.text(id="template-text",
                       class_="form-control mw-100",
                       rows="9")}}
        {% for error in wtform.text.errors %}
          <span class="wtf-error ds-error-message">{{ error }}</span>
        {% endfor %}
        </div>

        <div class="mt-4">
          <input class="btn btn-outline-primary" type="button" onclick="showPreview()" value="{{ _('Preview') }}" />
          <input class="btn btn-primary" type="submit" value="{{ _('Save') }}" />
        </div>
      </div>
    </div>
  </form>

  <div class="grid">
    <div class="g-col-12">
      <div id="preview" class="g-col-12 mt-4 p-3 text-bg-light" style="display:none">
        <div id="preview-text"><div>
      </div>
    </div>
  </div>

</div>

<script>
const inline_help_file_name = "site_invitationtemplate.j2.md";
const placeholders = {{ placeholders | tojson }}
var texts = {{ texts | tojson }}
var preview_cache = {}
var lang_code = null

function showPreview() {
  getPreview().then(function() {
    $('#preview-text').html(preview_cache[lang_code]);
    $('#preview').show()
    $('html, body').animate({
        scrollTop: $("#preview").offset().top -200
    }, 250);
  });
}
const textarea = document.getElementById('template-text')
$(function() {
  changeLanguage();
  $("form[name=inviteText]").focusin(function() {
    if (!$("input[type=submit]").is(":focus")) {
      $('#preview').hide()
      delete preview_cache[lang_code];
    }
  });
});
function changeLanguage() {
  lang_code = $('#language').val()
  setMessageValue()
  $('#preview').hide()
}
function setMessageValue() {
  if (texts[lang_code]) {
    $("#template-text").val(texts[lang_code])
  } else {
    $("#template-text").val(placeholders[lang_code])
  }
}
function getPreview() {
  return new Promise(function(resolve, reject) {
    if (Object.keys(preview_cache).includes(lang_code) && preview_cache[lang_code] !== "") {
      resolve()
      return
    }
    $.ajax({
      url : "{{ url_for('invite_bp.invite_preview') }}",
      type: "POST",
      dataType: "json",
      data: {"language": lang_code, "text": $("#template-text").val()},
      beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
      },
      success: function(data, textStatus, jqXHR)
      {
        if (data.preview) {
          preview_cache[lang_code] = data.preview
          resolve()
        }
      }
    });
  });
}
</script>

{% endblock %}

liberaforms/templates/site/look-and-feel.html
{% extends "base-backend.html" %}
{% block content %}

<!-- site_look_and_feel_page -->

<script src="{{ url_for('static', filename='vendor/color-wheel/reinvented-color-wheel.min.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/color-wheel/reinvented-color-wheel.min.css') }}">

<style>
.ds-color-palette span {
  display: inline-block;
  min-width: 2.9em;
  min-height: 2.9em;
  margin-right: -5px;
  margin-bottom: -6px;
  cursor: pointer;
}
</style>

<div class="ds-narrow-container">

  <div class="grid ds-header-title">
    <div class="g-col-12 ds-title-with-icon-return">
      <a href="{{ url_for('admin_bp.admin_panel')}}" arial-label="return"><i data-feather="arrow-left"></i></a>
      <h1>{{ _("Look and feel") }}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <p class="mb-0">{{ _("Configure this site's appearance.") }}</p>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <div class="card">
        <div class="card-body">
          <form name="nameForm" action="{{url_for('site_bp.change_name')}}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <label for="ds-change-site-name" class="form-label">{{ _("Site name") }}</label>
            <div>
              <input id="ds-change-site-name" class="form-control" type="text" name="sitename" value="{{site.name}}" required />
            </div>
            <div class="mt-4">
              <input class="btn btn-sm btn-primary" type="submit" value="{{ _('Save') }}" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="grid mt-4">
    <div class="g-col-12">
      <div class="card">
        <div class="card-body">
          <form name="iconForm" method="POST" action="{{url_for('site_bp.change_icon')}}" enctype=multipart/form-data >
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <label class="form-label">{{ _("Site logo") }}</label>
            <div class="form-group">
              <input type="file" name="file" class="form-control"
                     data-parsley-max-file-size="{{config['MAX_MEDIA_SIZE']}}"
                     data-parsley-file-mimetypes="image/png, image/jpeg"
                     required=True />
              <div class="form-text">{{ _("Keep the kilobytes to a minimum") }}</div>
            </div>
            <div class="mt-4">
              <a class="btn btn-sm btn-outline-secondary" role="button" href="{{url_for('site_bp.reset_icon')}}">{{ _("Use default") }}</a>
              <input class="btn btn-sm btn-primary" type="submit" value="{{ _('Upload') }}" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="grid mt-4">
    <div class="g-col-12">
      <div class="card">
        <div class="card-header">
          <h4>{{ _("Site colors") }}</h4>
        </div>
        <div class="card-body">

          <form name="colorForm" method="POST" action="{{url_for('site_bp.change_theme')}}">
            {{ wtcolorform.csrf_token }}
            {{ wtcolorform.font_color(id="font-color") }}
            <div>
              <label class="form-label">{{ _("Header font color") }}</label>
              <br />
              <div class="btn-group btn-toggle">
                {% set color = g.site.theme['navbar']['font_color'] %}
                <button id="light_font_button" type="button" class="btn btn-sm {% if color=='#ddd' %}btn-primary{% else %}btn-outline-secondary{% endif %}"
                        onclick="javascript:setLightFont()">
                  {{ _("Light") }}
                </button>
                <button id="dark_font_button" type="button" class="btn btn-sm {% if color=='#333' %}btn-primary{% else %}btn-outline-secondary{% endif %}"
                        onclick="javascript:setDarkFont()">
                  {{ _("Dark") }}
                </button>
              </div>
            </div>

            <div class="mt-4">
              <label class="form-label">{{ _("Primary color") }}
              <div class="ds-color-palette mt-2">
                <div id="color_wheel_container"></div>
              </div>
            </div>

            <div class="form-group mt-2">
              {{ wtcolorform.primary_color.label(class_="form-label") }}
              {{ wtcolorform.primary_color(class_="form-control") }}
              {% for error in wtcolorform.primary_color.errors %}
                <span class="wtf-error ds-error-message">{{ error }}</span>
              {% endfor %}
            </div>
            <div class="mt-4">
              <input class="btn btn-primary" type="submit" value="{%trans%}Save{%endtrans%}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
const inline_help_file_name = "site_lookandfeel.j2.md";
// change name script

const parsley_options = {
  errorsContainer: function (field) {
    return $(field.element).closest(".form-group")
  }
}
$('form[name=nameForm]').parsley()
$('form[name=iconForm]').parsley(parsley_options)

// change font color script
function setFontColor(color) {
  $(".ds-color-primary-level, .ds-color-primary-level:hover, .ds-color-primary-level:active, .ds-color-primary-level:focus").css('color', color)
}
function setLightFont() {
  $("#font-color").val("#ddd")
  setFontColor($("#font-color").val())
  $('#light_font_button').addClass('btn-primary')
                         .removeClass('btn-outline-secondary');
  $('#dark_font_button').removeClass('btn-primary')
                        .addClass('btn-outline-secondary');
}
function setDarkFont() {
  $("#font-color").val("#333")
  setFontColor($("#font-color").val())
  $('#light_font_button').removeClass('btn-primary')
                        .addClass('btn-outline-secondary');
  $('#dark_font_button').addClass('btn-primary')
                         .removeClass('btn-outline-secondary');
}

var colorWheel = new ReinventedColorWheel({
  // appendTo is the only required property. specify the parent element of the color wheel.
  appendTo: document.getElementById("color_wheel_container"),
  hex: "{{ g.site.theme['primary_color'] }}",

  // appearance
  wheelDiameter: 200,
  wheelThickness: 20,
  handleDiameter: 16,
  wheelReflectsSaturation: false,

  // handler
  onChange: function (color) {
    $("input[name=primary_color]").val(color.hex)
    $(".ds-main-navbar").css('backgroundColor', color.hex)
    $(".ds-wrapper-white").css('border-top-color', color.hex)
    $(".card").css('border-top-color', color.hex)
    $("#primary_color").val(color.hex)
  },
});

// https://stackoverflow.com/questions/6177454/can-i-force-jquery-cssbackgroundcolor-returns-on-hexadecimal-format
$.cssHooks.backgroundColor = {
    get: function(elem) {
        if (elem.currentStyle)
            var bg = elem.currentStyle["backgroundColor"];
        else if (window.getComputedStyle)
            var bg = document.defaultView.getComputedStyle(elem, null)
                                         .getPropertyValue("background-color");
        if (bg.search("rgb") == -1)
            return bg;
        else {
            bg = bg.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);
            function hex(x) {
                return ("0" + parseInt(x).toString(16)).slice(-2);
            }
            return "#" + hex(bg[1]) + hex(bg[2]) + hex(bg[3]);
        }
    }
}
$(function () {
  $('form[name=colorForm]').parsley().on('form:validate', function() {
    $('span[class=wtf-error]').remove()
  })
})

// change icon script
$(function () {
  $('form[name=iconForm]').parsley().on('field:validated', function() {
    var ok = $('.parsley-error').length === 0;
    $('.bs-callout-info').toggleClass('hidden', !ok);
    $('.bs-callout-warning').toggleClass('hidden', ok);
  })
});
window.Parsley.addValidator('fileMimetypes', {
  validateString: function(_value, requirement, parsleyInstance) {
    if (!window.FormData) {
      return true;
    }
    var file = parsleyInstance.$element[0].files;
    if (file.length == 0) {
      return true;
    }
    var allowedMimeTypes = requirement.replace(/\s/g, "").split(',');
    return allowedMimeTypes.indexOf(file[0].type) !== -1;
  },
  requirementType: 'string',
  messages: {
    {{ g.language }}: "{{ _('Please use a PNG or JPG file') }}"
  }
});
window.Parsley.addValidator('maxFileSize', {
  validateString: function(_value, maxSize, parsleyInstance) {
    if (!window.FormData) {
      return true;
    }
    var files = parsleyInstance.$element[0].files;
    return files.length != 1  || files[0].size <= maxSize;
 },
  requirementType: 'integer',
  messages: {
    {{ g.language }}: "{{ _('The file is too large. Max. %(size)s', size = human_readable_bytes(config['MAX_MEDIA_SIZE'])) }}"
  }
});
</script>

{% endblock %}