liberaforms/views/admin.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2020 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

import os
from datetime import datetime, timezone
from flask import current_app, g, request, render_template, redirect
from flask import flash, Blueprint, url_for, jsonify
from flask import send_file, after_this_request
from flask_babel import gettext as _
import flask_login
from liberaforms.domain.storage import StorageDomain
from liberaforms.domain import form as form_domain
from liberaforms.models.user import User
from liberaforms.models.form import Form
from liberaforms.models.formuser import FormUser
from liberaforms.models.invite import Invite
from liberaforms.models.schemas.invite import InviteSchema
from liberaforms.models.schemas.consent import ConsentSchema
from liberaforms.utils import auth
from liberaforms.utils import utils
from liberaforms.utils import chart_data
from liberaforms.utils.dispatcher import Dispatcher
from liberaforms.utils.exports import write_users_csv
from liberaforms.utils import tokens
from liberaforms.utils import wtf
from liberaforms.utils import i18n
from liberaforms.utils import form_helper

# from pprint import pprint

admin_bp = Blueprint('admin_bp', __name__,
                     template_folder='../templates/admin')


@admin_bp.route('/admin', methods=['GET'])
@auth.enabled_admin_required
def admin_panel():
    return render_template('admin-panel.html',
                           user=flask_login.current_user,
                           custom_languages=i18n.get_custom_languages(),
                           StorageDomain=StorageDomain,
                           goto=request.args.get("goto", None))

# User management

@admin_bp.route('/admin/users', methods=['GET'])
@auth.enabled_admin_required
def list_users():
    return render_template('list-users.html',
                           users=User.find_all(),
                           invites=Invite.find_all().count())

@admin_bp.route('/admin/user/<int:user_id>', methods=['GET'])
@flask_login.login_required
@auth.enabled_admin_required
def inspect_user(user_id):
    user = User.find(id=user_id)
    if not user:
        flash(_("User not found"), 'warning')
        return redirect(url_for('admin_bp.list_users'))
    return render_template('inspect-user.html',
                           user=user,
                           chart_data=chart_data.get_user_statistics(user),
                           human_readable_bytes=utils.human_readable_bytes)


@admin_bp.route('/admin/user/<int:user_id>/set-role/<string:role>', methods=['POST'])
@auth.enabled_admin_required__json
def set_role(user_id, role):
    user = User.find(id=user_id)
    if not user:
        return jsonify("Not found"), 404
    if role not in ('guest', 'editor', 'admin'):
        return jsonify("Invalid role"), 406
    if user.username != flask_login.current_user.username:
        # current_user cannot remove their own admin permission
        if user.set_role(role):
            user.save()
            admin_name = flask_login.current_user.username
            current_app.logger.info(f'USER - Admin "{admin_name}" changed user "{user.username}" role: {role}')
    return jsonify(role=user.role), 200


@admin_bp.route('/admin/user/<int:user_id>/toggle-blocked', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_user_blocked(user_id):
    user = User.find(id=user_id)
    if not user:
        return jsonify("Not found"), 404
    if user.id == flask_login.current_user.id:
        # current_user cannot disable themself
        return jsonify(blocked=False), 200
    blocked = user.toggle_blocked()
    admin_name = flask_login.current_user.username
    if blocked:
        current_app.logger.info(f'USER - Admin "{admin_name}" blocked user "{user.username}"')
    else:
        current_app.logger.info(f'USER - Admin "{admin_name}" unblocked user "{user.username}"')
    return jsonify(blocked=blocked), 200


@admin_bp.route('/admin/user/<int:user_id>/toggle-uploads-enabled', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_uploads_enabled(user_id):
    user = User.find(id=user_id)
    if not user:
        return jsonify("Not found"), 404
    return jsonify(uploads_enabled=user.toggle_uploads_enabled()), 200


@admin_bp.route('/admin/user/<int:user_id>/set-upload-limit', methods=['GET', 'POST'])
@auth.enabled_admin_required
def set_user_upload_limit(user_id):
    user = User.find(id=user_id)
    if not user:
        flash(_("User not found"), 'warning')
        return redirect(url_for('admin_bp.list_users'))
    wtform = wtf.UserUploadLimit()
    if wtform.validate_on_submit():
        result = f"{wtform.size.data.strip()} {wtform.unit.data.strip()}"
        bytes_limit: int = utils.string_to_bytes(result)
        user.set_uploads_limit(bytes_limit)
        user.set_disk_usage_alert()
        user.save()
        flash(_("Uploads limit updated OK"), 'success')
        return redirect(url_for('admin_bp.inspect_user', user_id=user.id))
    if request.method == 'GET':
        bytes_str = utils.human_readable_bytes(user.uploads_limit)
        wtform.size.data = float(bytes_str[:-3])
        wtform.unit.data = bytes_str[-2:]
    default = [current_app.config['DEFAULT_USER_UPLOADS_LIMIT'][:-3],
               current_app.config['DEFAULT_USER_UPLOADS_LIMIT'][-2:]]
    return render_template('user-upload-limit.html',
                           user=user, default=default, wtform=wtform)


@admin_bp.route('/admin/user/<int:user_id>/delete', methods=['GET', 'POST'])
@auth.enabled_admin_required
def delete_user(user_id):
    user = User.find(id=user_id)
    if not user:
        flash(_("User not found"), 'warning')
        return redirect(url_for('admin_bp.list_users'))
    if request.method == 'POST' and 'username' in request.form:
        if user.is_root_user():
            flash(_("Cannot delete root user"), 'warning')
            return redirect(url_for('admin_bp.inspect_user', user_id=user.id))
        if user.id == flask_login.current_user.id:
            flash(_("Cannot delete yourself"), 'warning')
            return redirect(url_for('admin_bp.inspect_user', user_id=user.id))
        if user.username == request.form['username']:
            user.delete()
            admin_name = flask_login.current_user.username
            current_app.logger.info(f'USER - Admin "{admin_name}" deleted user "{user.username}"')
            flash(_("Deleted user '%(name)s'", name=user.username), 'success')
            return redirect(url_for('admin_bp.list_users'))
        flash(_("Username does not match"), 'warning')
    return render_template('delete-user.html', user=user)


@admin_bp.route('/admin/user/<int:user_id>/stats', methods=['GET'])
@auth.enabled_admin_required__json
def get_user_usage_graph_data(user_id):
    user = User.find(id=user_id)
    if not user:
        return jsonify("Not found"), 404
    try:
        offset = int(request.args.get("year-offset", 0))
        return jsonify(chart_data=chart_data.get_user_statistics(user, offset_year=offset))
    except:
        current_app.logger.debug("APP - Failed to get user usage graph data")
        return jsonify("Not acceptable"), 406


@admin_bp.route('/admin/users/csv', methods=['GET'])
@auth.enabled_admin_required
def csv_users():
    csv_file = write_users_csv(User.find_all())

    @after_this_request
    def remove_file(response):
        os.remove(csv_file)
        return response
    return send_file(csv_file, mimetype="text/csv", as_attachment=True)


#  Form management

@admin_bp.route('/admin/forms', methods=['GET'])
@auth.enabled_admin_required
def list_forms():
    return render_template('list-forms.html')


@admin_bp.route('/admin/form/<int:form_id>', methods=['GET'])
@flask_login.login_required
@auth.enabled_admin_required
@auth.instantiate_form()
@form_domain.expire_on_date_condition
def inspect_form(form_id, **kwargs):
    form = kwargs["form"]
    return render_template('admin/form-details.html',
                           form=form,
                           FormUser=FormUser,
                           viewer_role="admin",
                           invites=Invite.find_all(granted_form=form.id),
                           human_readable_bytes=utils.human_readable_bytes,
                           status_badges=form_helper.status_badges)


# ## Previews

@admin_bp.route('/admin/form/<int:form_id>/preview', methods=['GET'])
@auth.enabled_admin_required
@auth.instantiate_form()
def preview_form(form_id, **kwargs):
    form = kwargs['form']
    max_attach_size = utils.human_readable_bytes(current_app.config['MAX_ATTACHMENT_SIZE'])
    consents = form.get_consents()
    return render_template('form/preview-form.html',
                           form=form,
                           consents=ConsentSchema(many=True).dump(consents),
                           upload_media_form=wtf.UploadMedia(),
                           human_readable_bytes=utils.human_readable_bytes,
                           viewer_role="admin",
                           go_back_url=url_for('admin_bp.inspect_form', form_id=form.id),
                           max_attach_size=max_attach_size)


@admin_bp.route('/admin/form/<int:form_id>/preview/thank-you-page', methods=['GET'])
@auth.enabled_admin_required
@auth.instantiate_form()
def preview_thankyou(form_id, **kwargs):
    form = kwargs['form']
    after_submit_text = form.get_after_submit_text_html()
    edition_link = None
    edition_link = form.get_edit_answer_link() if form.anon_edition else None
    return render_template('form/preview-thankyou.html',
                           form=form,
                           after_submit_text=after_submit_text,
                           edition_link=edition_link,
                           viewer_role="admin",
                           go_back_url=url_for('admin_bp.inspect_form', form_id=form.id))


@admin_bp.route('/admin/form/<int:form_id>/preview/expired-page', methods=['GET'])

liberaforms/templates/form/partials/answer-options.html
<!-- form_answer_options -->

<div class="card">
  <div class="card-header"><h2>{{ _("Answers") }}</h2></div>
  <div class="card-body">
    <ul class="ds-list-group">
      {% if form_user != None and viewer_role != "admin" %}
      <li>
        <span>{{ _("Last answer") }}</span>
        <span>{{ form.get_last_answer_date() }}</span>
      </li>
      {% set disk_usage = form.get_disk_usage() %}
      {% if form.has_file_field() or disk_usage > 0 %}
      <li>
        <span>{{ _("Attached files") }}</span>
        <span>{{ human_readable_bytes(disk_usage) }}</span>
      </li>
      {% endif %}
      <li>
        <span>{{ _("Notify me on each new answer") }}</span>
        <div id="toggle_notification" class="btn-group btn-toggle">
          <button id="notification_true" class="btn btn-sm {% if form_user['notifications']['newAnswer'] %}btn-primary{% else %}btn-outline-secondary{% endif %}">{{ _("True") }}</button>
          <button id="notification_false" class="btn btn-sm {% if not form_user['notifications']['newAnswer'] %}btn-primary{% else %}btn-outline-secondary{% endif %}">{{ _("False") }}</button>
        </div>
      </li>
      {% endif %}
      <li>
        <span>{{ _("Allow users to edit their answers") }}</span>
        <div id="toggle_anon_edition" class="btn-group btn-toggle">
          <button id="anon_edition_true" class="btn btn-sm {% if form.anon_edition %}btn-primary{% else %}btn-outline-secondary{% endif %}">{{ _("True") }}</button>
          <button id="anon_edition_false" class="btn btn-sm {% if not form.anon_edition %}btn-primary{% else %}btn-outline-secondary{% endif %}">{{ _("False") }}</button>
        </div>
      </li>
      <li>
        <span>{{ _("Notify me when they edit their answers") }}</span>
        {% set anon_answer_edition = form_user["notifications"]["anon_answer_edition"] %}
        <div class="btn-group btn-toggle">
          <button id="notify_answer_edition_true" class="notify-on-answer-edition btn btn-sm {% if anon_answer_edition %}btn-primary{% else %}btn-outline-secondary{% endif %}"
                  {% if not form.anon_edition %}disabled{% endif %}>
              {{ _("True") }}
          </button>
          <button id="notify_answer_edition_false" class="notify-on-answer-edition btn btn-sm {% if not anon_answer_edition %}btn-primary{% else %}btn-outline-secondary{% endif %}"
                  {% if not form.anon_edition %}disabled{% endif %}>
              {{ _("False") }}
          </button>
        </div>
      </li>
    </ul>
  </div>
</div>

<script>
  // notify me on new answer
  document.getElementById('toggle_notification').addEventListener('click', function(evt){
      $.ajax({
          url : "{{url_for('form_bp.toggle_new_answer_notification', form_id=form.id)}}",
          type: "POST",
          dataType: "json",
          beforeSend: function(xhr, settings) {
              if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token() }}")
              }
          },
          success: function(data, textStatus, jqXHR)
          {
              if (data.notification == true) {
                  $('#notification_true').addClass('btn-primary')
                                         .removeClass('btn-outline-secondary');
                  $('#notification_false').removeClass('btn-primary')
                                          .addClass('btn-outline-secondary');
              }
              else if (data.notification == false) {
                  $('#notification_true').removeClass('btn-primary')
                                         .addClass('btn-outline-secondary');
                  $('#notification_false').addClass('btn-primary')
                                          .removeClass('btn-outline-secondary');
              }
          }
      });
  });
  document.getElementById('toggle_anon_edition').addEventListener('click', function(evt){
    $.ajax({
      url : "{{url_for('form_bp.toggle_anon_edition', form_id=form.id)}}",
      type: "POST",
      dataType: "json",
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
          xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token() }}")
        }
      },
      success: function(data, textStatus, jqXHR)
      {
        if (data.anon_edition == true) {
          $('#anon_edition_true').addClass('btn-primary')
                                 .removeClass('btn-outline-secondary');
          $('#anon_edition_false').removeClass('btn-primary')
                                  .addClass('btn-outline-secondary');
          $(".notify-on-answer-edition").prop("disabled", false)
        }
        else if (data.anon_edition == false) {
          $('#anon_edition_true').removeClass('btn-primary')
                                 .addClass('btn-outline-secondary');
          $('#anon_edition_false').addClass('btn-primary')
                                  .removeClass('btn-outline-secondary');
          $("#notify_answer_edition_true").removeClass('btn-primary')
                                          .addClass('btn-outline-secondary');
          $("#notify_answer_edition_false").addClass('btn-primary')
                                           .removeClass('btn-outline-secondary');
          $(".notify-on-answer-edition").prop("disabled", true)
        }
      }
    });
  });
  $(".notify-on-answer-edition").on('click', function(evt) {
    $.ajax({
      url : "{{ url_for('form_bp.toggle_notify_on_answer_edition', form_id=form.id) }}",
      type: "POST",
      dataType: "json",
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      },
      success: function(data, textStatus, jqXHR)
      {
        if (data.notify_answer_edition == true) {
          $('#notify_answer_edition_true').addClass('btn-primary')
                                          .removeClass('btn-outline-secondary');
          $('#notify_answer_edition_false').removeClass('btn-primary')
                                           .addClass('btn-outline-secondary');
        }
        else if (data.notify_answer_edition == false) {
          $('#notify_answer_edition_true').removeClass('btn-primary')
                                          .addClass('btn-outline-secondary');
          $('#notify_answer_edition_false').addClass('btn-primary')
                                           .removeClass('btn-outline-secondary');
        }
      }
    });
  });
</script>

liberaforms/templates/form/partials/api-endpoint.html
<!-- form_api_endpoints -->

{% set is_auth_enabled = True if form.endpoint_auth and form.endpoint_auth.enabled else False %}

<div class="card">
  <div class="card-header">
    <h2>API endpoints</h2>
  </div>
  <div class="card-body">
    <ul class="ds-list-group">
      <li>
        <span>JWT authorization</span>
        <span id="toggle_endpoint_auth" class="btn-group btn-toggle">
          <button id="endpoint_auth_true" class="btn btn-sm {% if is_auth_enabled %}btn-primary{% else %}btn-outline-secondary{% endif %}">{{ _("Enable") }}</button>
          <button id="endpoint_auth_false" class="btn btn-sm {% if not is_auth_enabled %}btn-primary{% else %}btn-outline-secondary{% endif %}">{{ _("Disable") }}</button>
        </span>
      </li>
      <li>
        <span>Authorization token</span>
        {% set href = 'href=javascript:void(0);' if is_auth_enabled else "" %}
        <span><a id="copy_token_link" {{href}} onclick="copyToCLipboard()">{{_("Copy to clipboard")}}</a></span>
      </li>
      <li>
        <span>GET <span class="text-lowercase">{{ _("Form") }}</span></span>
        <span>{{ url_for('api_bp.form_info', form_id=form.id, _external=True) }}</span>
      </li>
      <li>
        <span>GET <span class="text-lowercase">{{ _("Answers") }}</span></span>
        <span>{{ url_for('api_bp.form_answers', form_id=form.id, _external=True) }}</span>
      </li>
    </ul>
  </div>
</div>

{% set auth_header_value = form.endpoint_auth.get_authorization_header_value() if is_auth_enabled else "" %}
<input id="authorization_header_value" type="hidden" value="{{auth_header_value}}" />


<script>
document.getElementById('toggle_endpoint_auth').addEventListener('click', function(evt){
  $.ajax({
    url : "{{url_for('form_bp.toggle_endpoint_auth', form_id=form.id)}}",
    type: "POST",
    dataType: "json",
    beforeSend: function(xhr, settings) {
      if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    },
    success: function(data, textStatus, jqXHR)
    {
      if (data.enabled == true) {
        $('#endpoint_auth_true').addClass('btn-primary').removeClass('btn-outline-secondary');
        $('#endpoint_auth_false').removeClass('btn-primary').addClass('btn-outline-secondary');
        $("#authorization_header_value").val(data.authorization_header_value)
        $("#copy_token_link").attr("href", "javascript:void(0);")
      }
      else if (data.enabled == false) {
        $('#endpoint_auth_true').removeClass('btn-primary').addClass('btn-outline-secondary');
        $('#endpoint_auth_false').addClass('btn-primary').removeClass('btn-outline-secondary');
        $("#authorization_header_value").val("")
        $("#copy_token_link").removeAttr("href")
      }
    }
  });
});
function copyToCLipboard() {
  let authorization_header_value = $("#authorization_header_value").val()
  if (authorization_header_value == "") {
    return
  }
  navigator.clipboard.writeText(authorization_header_value)
}
</script>

liberaforms/templates/form/partials/context-menu.html
<nav class="ds-contextual-menu-form navbar-expand-lg text-end" role="navigation">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#contextualMenuForm" aria-controls="contextualMenuForm" aria-expanded="false" aria-label="Toggle navigation">
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-vertical" aria-hidden="true"><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>
  </button>
  <div class="collapse navbar-collapse" id="contextualMenuForm">
    <ul class="nav nav-pills">
      {% if viewer_role == "editor" %}
        <li class="nav-item">
          {% if active_item == 'settings' %}
            {# Can't do this because of nav-pills!!
            if sub_option %}
              {% set active = "btn-outline-primary" %}
            {% else %}
              {% set active = "active" %}
            {% endif #}
            {% set active = "active" %}
          {% else %}
            {% set active = "" %}
          {% endif %}
          <a class="nav-link {{ active }}" href="{{ url_for('form_bp.inspect_form', form_id=form.id) }}">{{ _("Configuration") }}</a>
        </li>
        <li class="nav-item">
          {% if active_item == 'options' %}
            {% set active = "active" %}
          {% else %}
            {% set active = "" %}
          {% endif %}
          <a class="nav-link {{ active }}" href="{{ url_for('form_bp.form_details', form_id=form.id) }}">{{ _("Options") }}</a>
        </li>
        <li class="nav-item">
          {% if active_item == 'answers' %}
            {% set active = "active" %}
            {% set item_link = "#" %}
          {% else %}
            {% set active = "" %}
          {% endif %}
          {% set item_link = url_for('answers_bp.list', form_id=form.id) %}
          <a class="nav-link {{ active }}" href="{{ item_link }}">{{ _("Answers") }} <span class="badge bg-light text-dark">{{ total_answers }}</span></a>
        </li>
        <li class="nav-item">
          {% if active_item == 'preview' %}
            {% set active = "active" %}
            {% set item_link = "#" %}
          {% else %}
            {% set active = "" %}
            {% set item_link = url_for('form_bp.preview', form_id=form.id) %}
          {% endif %}
          <a class="nav-link {{ active }}" href="{{ item_link }}">{{ _("Preview") }}</a>
        </li>
      {% endif %}

      {% if viewer_role == "admin" %}
        <li class="nav-item">
          {% if active_item == 'options' %}
            {% set active = "active" %}
            {% set item_link = "#" %}
          {% else %}
            {% set active = "" %}
            {% set item_link = url_for('admin_bp.inspect_form', form_id=form.id) %}
          {% endif %}
          <a class="nav-link {{ active }}" href="{{ item_link }}">{{ _("Details") }}</a>
        </li>
        <li class="nav-item">
          {% if active_item == 'preview' %}
            {% set active = "active" %}
            {% set item_link = "#" %}
          {% else %}
            {% set active = "" %}
            {% set item_link = url_for('admin_bp.preview_form', form_id=form.id) %}
          {% endif %}
          <a class="nav-link {{ active }}" href="{{ item_link }}">{{ _("Preview") }}</a>
        </li>
      {% endif %}

      {% if viewer_role == "guest" %}
        <li class="nav-item">
          {% if active_item == 'answers' %}
            {% set active = "active" %}
            {% set item_link = "#" %}
          {% else %}
            {% set active = "" %}
            {% set item_link = url_for('answers_bp.list', form_id=form.id) %}
          {% endif %}
          <a class="nav-link {{ active }}" href="{{ item_link }}">{{ _("Answers") }} <span class="badge bg-light text-dark">{{ total_answers }}</span></a>
        </li>
        <li class="nav-item">
          {% if active_item == 'preview' %}
            {% set active = "active" %}
            {% set item_link = "#" %}
          {% else %}
            {% set active = "" %}
            {% set item_link = url_for('form_bp.preview', form_id=form.id) %}
          {% endif %}
          <a class="nav-link {{ active }}" href="{{ item_link }}">{{ _("Preview") }}</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

liberaforms/templates/form/partials/form-context.html
{% if viewer_role is not defined %}
  {% set viewer_role = "editor" %}
{% endif %}

<div class="grid align-items-start align-items-lg-end ds-header-title-with-button">
  <div class="g-col-6 g-col-lg-5">
    <h1 class="ds-context-menu-title">
      {% if viewer_role == "editor" and active_item == 'options' and sub_option != True %}
      <a href="#" class="ds-change-form-name text-decoration-none" onclick="window.location='{{url_for('form_bp.change_name', form_id=form.id)}}'">{{ form.name }}
      <i data-feather="edit" width="18" height="18" aria-hidden="true"></i></a>
      {% else %}
      <span>{% if viewer_role == "admin" %}{{ form.slug }}{% else %}{{ form.name }}{% endif %}</span>
      {% endif %}
    </h1>
  </div>
  <div class="g-col-6 g-col-lg-7">
    {% if not without_menu %}
      {% if is_form_editor is not defined %}
        {% set is_form_editor = form.is_editor(current_user.id) %}
      {% endif %}
      {% if is_form_guest is not defined %}
        {% set is_form_guest = form.is_guest(current_user.id) %}
      {% endif %}
      {% if not total_answers is defined %}
        {% set total_answers = form.get_total_answers() %}
      {% endif %}

      {% include 'form/partials/context-menu.html' %}
    {% endif %}
  </div>
</div>

liberaforms/templates/form/partials/preview-nav-menu.html
<!-- preview_nav_menu -->

{% if viewer_role is not defined %}
  {% set viewer_role = "guest" %}
{% endif %}

{% if viewer_role != "admin" %}
{% set form_can_expire = form.can_expire() %}

<nav class="navbar-expand-lg ds-accions-look-and-feel">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#preview-navigation" aria-controls="previewNav" aria-expanded="false" aria-label="Preview page navigation">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
  </button>
  <div class="navbar-collapse collapse mt-1 gap-2" id="preview-navigation">
    {% if not (expired_form_preview and not form_can_expire) %}
    <button class="btn btn-outline-primary btn-sm" type="button" onClick="location.href='{{url_for('form_bp.preview', form_id=form.id)}}'">{{ _("Form") }}</button>
    <button class="btn btn-outline-primary btn-sm" type="button" onClick="location.href='{{url_for('form_bp.preview_thankyou', form_id=form.id)}}'">{{ _("Thanks") }}</button>
      {% if form_can_expire %}
      <button class="btn btn-outline-primary btn-sm" type="button" onClick="location.href='{{url_for('form_bp.preview_expired', form_id=form.id)}}'">{{ _("Expired") }}</button>
      {% endif %}
    {% endif %}
  </div>
</nav>

{% endif %}
{% if viewer_role == "admin" %}

<nav class="navbar-expand-lg ds-accions-look-and-feel">
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#preview-navigation" aria-controls="previewNav" aria-expanded="false" aria-label="Preview page navigation">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
  </button>
  <div class="navbar-collapse collapse mt-1 gap-2" id="preview-navigation">
    <button class="btn btn-outline-primary btn-sm" type="button" onClick="location.href='{{url_for('admin_bp.preview_form', form_id=form.id)}}'">{{ _("Form") }}</button>
    <button class="btn btn-outline-primary btn-sm" type="button" onClick="location.href='{{url_for('admin_bp.preview_thankyou', form_id=form.id)}}'">{{ _("Thank you") }}</button>
    <button class="btn btn-outline-primary btn-sm" type="button" onClick="location.href='{{url_for('admin_bp.preview_expired', form_id=form.id)}}'">{{ _("Expired") }}</button>
  </div>
</nav>

{% endif %}