liberaforms/views/consent.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2022 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

import json
from sqlalchemy import update
from flask import Blueprint, request, g, flash, jsonify
from flask import render_template, url_for, redirect
import flask_login
from flask_babel import gettext as _
from liberaforms import db
from liberaforms.models.consent import Consent
from liberaforms.models.form import Form
from liberaforms.models.formconsent import FormConsent
from liberaforms.models.schemas.consent import ConsentSchema
from liberaforms.models.schemas.form import FormSchema
from liberaforms.utils import auth
from liberaforms.utils import utils
from liberaforms.utils import sanitizers
from liberaforms.utils import wtf
from liberaforms.utils import i18n

# from pprint import pprint

consent_bp = Blueprint('consent_bp', __name__,
                       template_folder='../templates/consent')


@auth.enabled_editor_required
def handle_edit_consent_request(consent, scope=None):
    """Reusable code to create/edit consent texts in site, user and form views."""
    wtform = wtf.ConsentText()
    wtform.language_selector.choices = i18n.get_language_select_choices()
    if wtform.validate_on_submit():
        kwargs = {
            "name": wtform.name.data,
            "label": wtform.label.data,
            "md_text": wtform.md_text.data,
            "checkbox_label": wtform.checkbox_label.data,
            "required": utils.str2bool(wtform.required.data),
        }
        wizard = json.loads(wtform.wizard.data) if wtform.wizard.data else None
        if wizard:
            kwargs["wizard"] = wizard
        consent.save_texts(wtform.language.data, **kwargs)
        flash(_("Privacy statement saved OK"), 'success')
    if request.method == 'GET':
        wtform.name.data = consent.name
        lang_code = g.site.language if scope == "site" else g.language
        wtform.language.data = lang_code
        label = consent.label[lang_code] if lang_code in consent.label.keys() else ""
        md_text = consent.text[lang_code]["markdown"] if lang_code in consent.text.keys() else ""
        checkbox = consent.checkbox_label[lang_code] if lang_code in consent.checkbox_label.keys() else ""
        wtform.label.data = label
        wtform.md_text.data = md_text
        wtform.checkbox_label.data = checkbox
    wtform.required.data = consent.required
    return wtform


@consent_bp.route('/data-consent/preview', methods=['POST'])
@auth.enabled_editor_required__json
def get_preview():
    if not ("lang_code" in request.form and "required" in request.form):
        return jsonify("Not acceptable"), 406
    lang_code = request.form["lang_code"]
    kwargs = {}
    kwargs["required"] = utils.str2bool(request.form["required"])
    if "label" in request.form:
        kwargs["label"] = {lang_code: request.form["label"]}
    if "title" in request.form:
        kwargs["title"] = {lang_code: request.form["title"]}
    if "checkbox_label" in request.form:
        kwargs["checkbox_label"] = {lang_code: request.form["checkbox_label"]}
    if "md_text" in request.form:
        markdown = sanitizers.remove_html_tags(request.form["md_text"])
        html = sanitizers.markdown_to_html(markdown)
        html = sanitizers.bleach_text(html)
        kwargs["text"] = {lang_code: {"markdown": markdown,
                                      "html": html}}
    else:
        kwargs["text"] = {lang_code: {"markdown": "", "html": ""}}
    consent = ConsentSchema(lang_code=lang_code).dump(Consent(**kwargs))
    html = render_template('consent/partials/consent.html', consent=consent)
    return jsonify(html=html), 200


@consent_bp.route('/data-consent/<string:scope>/wizard', methods=['GET'])
@consent_bp.route('/data-consent/<int:consent_id>/<string:scope>/wizard', methods=['GET'])
@consent_bp.route('/data-consent/<int:consent_id>/<string:scope>/<int:form_id>/wizard', methods=['GET'])
@auth.enabled_editor_required__json
def get_wizard_data(scope, consent_id=None, form_id=None):
    """Return data required by wizard."""
    settings = {'scope': scope}
    if scope == "site" and flask_login.current_user.is_admin():
        organization = g.site.data_protection["organization"]
        settings["enforce_org"] = False
    else:
        organization = flask_login.current_user.get_data_protection_org()
        settings["enforce_org"] = g.site.data_protection["enforce_org"]
    consent = None
    if consent_id and scope == "site" and flask_login.current_user.is_admin():
        consent = Consent.find(id=consent_id, site_id=g.site.id)
    user_id = flask_login.current_user.id
    if consent_id and scope == "user":
        consent = Consent.find(id=consent_id, user_id=user_id)
    if consent_id and scope == "form" and form_id:
        form_consent = FormConsent.find(consent_id=consent_id, form_id=form_id)
        if not (form_consent and form_consent.form.is_editor(user_id)):
            return jsonify("Not found"), 404
        consent = form_consent.consent
    wizard = consent.wizard if consent else {}
    return jsonify(settings=settings,
                   default_organization=organization,
                   wizard=wizard), 200


@consent_bp.route('/data-consent/user/organization', methods=['PATCH'])
@auth.enabled_editor_required__json
def set_user_default_organization():
    data = request.get_json()
    profile = {}
    if "is_public_administration" in data and isinstance(data["is_public_administration"], bool):
        profile["is_public_administration"] = data["is_public_administration"]
    if "name" in data:
        profile["name"] = sanitizers.remove_html_tags(data["name"])
    if "email" in data:
        profile["email"] = sanitizers.remove_html_tags(data["email"])
    if "url" in data:
        profile["url"] = sanitizers.remove_html_tags(data["url"])
    if len(profile.keys()) != 4:
        return jsonify("Not acceptable"), 406
    flask_login.current_user.data_protection = profile
    flask_login.current_user.save()
    return jsonify("Patched"), 200


@consent_bp.route('/data-consent/accept-wizard-disclaimer', methods=['POST'])
@auth.enabled_editor_required__json
def accept_wizard_disclaimer():
    preference = not flask_login.current_user.preferences["wizard_disclaimer"]
    flask_login.current_user.preferences["wizard_disclaimer"] = preference
    flask_login.current_user.save()
    return jsonify(is_disclaimer_accepted=preference), 200


@consent_bp.route('/data-consent/<string:scope>/<int:consent_id>/forms', methods=['GET'])
@auth.enabled_editor_required__json
def attached_forms(scope, consent_id):
    """ Return a list of forms that use this consent """
    def get_consent_forms(consent_id):
        forms = []
        for form in FormConsent.find_all(consent_id=consent_id):
            forms.append(form.form)
        return forms
    if scope == "site" and flask_login.current_user.is_admin():
        consent = Consent.find(id=consent_id, site_id=g.site.id)
        if not consent:
            return jsonify("Not found"), 404
        if consent.enforced:
            forms = Form.find_all()
        else:
            forms = get_consent_forms(consent.id)
        return jsonify(forms=FormSchema(url_as_admin=True, many=True).dump(forms[:60])), 200
    if scope == "user":
        consent = Consent.find(id=consent_id,
                               user_id=flask_login.current_user.id)
        if not consent:
            return jsonify("Not found"), 404
        forms = get_consent_forms(consent.id)
        return jsonify(forms=FormSchema(url_as_editor=True, many=True).dump(forms[:60])), 200
    return jsonify("Not acceptable"), 406


@consent_bp.route('/data-consent/<string:scope>/<int:consent_id>/copy/forms', methods=['GET'])
@auth.enabled_editor_required__json
def template_forms(scope, consent_id):
    """ Return a list of forms that use a copy this consent """
    forms = []
    def get_consent_forms(consent_id):
        for form in FormConsent.find_all(consent_id=consent_id):
            forms.append(form.form)
    if scope == "site" and flask_login.current_user.is_admin():
        consent = Consent.find(id=consent_id, site_id=g.site.id)
        if not consent:
            return jsonify("Not found"), 404
        for consent in Consent.find_all(template_id=consent_id):
            get_consent_forms(consent.id)
        return jsonify(forms=FormSchema(url_as_admin=True, many=True).dump(forms[:60])), 200
    if scope == "user":
        consent = Consent.find(id=consent_id,
                               user_id=flask_login.current_user.id)
        if not consent:
            return jsonify("Not found"), 404
        for consent in Consent.find_all(template_id=consent_id):
            get_consent_forms(consent.id)
        return jsonify(forms=FormSchema(url_as_editor=True, many=True).dump(forms[:60])), 200
    return jsonify("Not acceptable"), 406


# List consents


@consent_bp.route('/site/data-consent', methods=['GET'])
@auth.enabled_admin_required
def list_site_data_consents():
    consents = ConsentSchema(many=True).dump(g.site.consents)
    return render_template('site/list-consents.html',
                           consents=consents,
                           Form=Form,
                           FormConsent=FormConsent)


@consent_bp.route('/user/data-consent', methods=['GET'])
@auth.enabled_editor_required
def list_user_data_consents():
    consents = ConsentSchema(many=True).dump(flask_login.current_user.consents)
    return render_template('user/list-consents.html',
                           consents=consents,
                           FormConsent=FormConsent)


@consent_bp.route('/form/<int:form_id>/data-consent', methods=['GET'])
@auth.enabled_editor_required
@auth.instantiate_form(allow_admin=False)
def list_form_data_consents(form_id, **kwargs):
    form = kwargs['form']
    consents = flask_login.current_user.get_available_consents()

liberaforms/templates/consent/wizard.html
{% extends "base-backend.html" %}
{% block content %}

<!-- wizard_page -->

{% set show_continue_button = consent_url.endswith("/new") and consent_url != go_back_url %}

<div class="grid align-items-center ds-header-title-with-button">
  <div class="g-col-12 {% if show_continue_button %}g-col-md-8{%endif%} ds-title-with-icon-return">
    <a href="#" arial-label="return" onclick="go_back()"><i data-feather="arrow-left"></i></a>
    <h1>{{ _("Privacy statement wizard") }} (beta)</h1>
  </div>
  {% if show_continue_button %}
  <div class="g-col-12 g-col-md-4">
    <a class="btn btn-sm btn-primary" role="button" href="{{ consent_url }}">{{ _("Continue without the wizard") }}</a>
  </div>
  {% endif %}
</div>

<div class="grid mt-3">
  <div class="g-col-12">
    <p class="mb-1">
      {{ _("Answer these questions and copy the result") }}.
      <a href="#" onclick="toggleInlineHelp('wizard.j2.md')">{{ _("Learn more") }}</a>
    </p>
    <p class="mb-0">
      {% set dislaimer_link = '<a href="#" data-bs-toggle="modal" data-bs-target="#disclaimer-modal">%s</a>' % _("Disclaimer") %}
      {{ _("Please read our %(dislaimer_link)s", dislaimer_link=dislaimer_link|safe ) }}
    </p>
  </div>
</div>

{% set is_disclaimer_accepted = current_user.preferences["wizard_disclaimer"] %}
{# save the changing value here for the Vue component to get on Copy #}
<input id="is_disclaimer_accepted" type="hidden" value="{{is_disclaimer_accepted|tojson}}" />

<div class="ds-wrapper-white mt-3">
  <div vue-component="gdpr-wizard"
       data-data_endpoint="{{ endpoint }}"
       data-org_endpoint="{{ url_for('consent_bp.set_user_default_organization') }}"
       data-consent_id="{{ consent_id if consent_id else '' }}"
       data-consent_url="{{ consent_url }}"
       data-data_law="{{ g.site.data_protection['law'] }}"
       data-ui_language="{{ g.language }}"
       data-fallback_consent_language="{{ g.site.language if scope=='site' else g.language }}"
       data-csrf_token="{{ csrf_token() }}">
  </div>
</div>

<div id="disclaimer-modal" class="modal fade" tabindex="-1" aria-labelledby="disclaimer-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="disclaimer-modal-label">{{ _("Wizard disclaimer") }}</h5>
        <button type="button" data-bs-dismiss="modal" aria-label="Close">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x" aria-hidden="true"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
        </button>
      </div>
      <div class="modal-body">
        {{ disclaimer|safe }}
      </div>
      <div class="modal-footer justify-content-between">
        <div class="form-check my-3">
          <label class="form-check-label fw-bold" for="disclaimer-check">
            {{ _("I have read and understood") }}<span class="ds-required" arial-label="required"></span>
          </label>
          <input id="disclaimer-check" type="checkbox" class="form-check-input consent" data-bs-dismiss="modal" {% if is_disclaimer_accepted %}checked{% endif %} onclick="setWizardDisclaimerPref()" />
        </div>
      </div>
    </div>
  </div>
</div>
<input id="vue_modal_hook" type="hidden" />

<script src="/static/js/gdpr-wizard/gdpr-wizard.js"></script>

<script>
const inline_help_file_name = "wizard.j2.md";

$("#vue_modal_hook").change(function() {
  let modal = new bootstrap.Modal(document.getElementById('disclaimer-modal'))
  modal.show()
});
function setWizardDisclaimerPref() {
  $.ajax({
      url : "{{url_for('consent_bp.accept_wizard_disclaimer')}}",
      type: "POST",
      processData: false,
      contentType: false,
      beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
      },
      success: function(data, textStatus, jqXHR)
      {
        $("#disclaimer-modal").find("input[type=checkbox]").prop("selected", data.is_disclaimer_accepted)
        $("#is_disclaimer_accepted").val(data.is_disclaimer_accepted)
      }
  });
}
function go_back() {
  window.sessionStorage.removeItem('wizard')
  window.location = "{{ go_back_url }}"
}
</script>

{% endblock %}