liberaforms/views/media.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2021 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

from flask import g, request, render_template, redirect, session
from flask import Blueprint, current_app, jsonify, url_for
from flask_babel import gettext as _
import flask_login
from liberaforms.models.media import Media
from liberaforms.models.schemas.media import MediaSchema
from liberaforms.utils import auth
from liberaforms.utils import utils
from liberaforms.utils import wtf

#from pprint import pprint

media_bp = Blueprint('media_bp',
                     __name__,
                     template_folder='../templates/media')


@media_bp.route('/media/save', methods=['POST'])
@auth.enabled_editor_required__json
def save_media():
    if not flask_login.current_user.can_upload():
        return jsonify(image_url=""), 406
    wtform = wtf.UploadMedia()
    if not wtform.validate_on_submit():
        return jsonify(errors=wtform.errors), 406
    media = Media()
    saved = media.save_media(flask_login.current_user,
                             request.files['media_file'],
                             request.form['alt_text'])
    if saved:
        if flask_login.current_user.set_disk_usage_alert():
            flask_login.current_user.save()
        total_usage = flask_login.current_user.total_uploads_usage()
        media_usage = flask_login.current_user.media_usage()
        percent = "{:.2f} %".format((total_usage * 100) / flask_login.current_user.uploads_limit)
        return jsonify(
            media=MediaSchema().dump(media),
            usage_percent=percent,
            total_usage=total_usage,
            media_human_usage=utils.human_readable_bytes(media_usage),
            total_human_usage=utils.human_readable_bytes(total_usage),
            show_alert=bool(flask_login.current_user.alerts)
        ), 200
    return jsonify(False), 406


@media_bp.route('/user/media', methods=['GET'])
@auth.enabled_editor_required
def list_user_media():
    if not flask_login.current_user.uploads_enabled:
        return redirect(url_for('user_bp.user_settings',
                                username=flask_login.current_user.username))
    return render_template('list-media.html',
                           human_readable_bytes=utils.human_readable_bytes,
                           wtform=wtf.UploadMedia())


@media_bp.route('/user/media/thumbnails', methods=['GET'])
@auth.enabled_editor_required__json
def user_media_thumbnails():
    media = Media.find_all(user_id=flask_login.current_user.id)
    media = MediaSchema(many=True, only=('id', 'thumbnail_url', 'alt_text')).dump(media)
    return jsonify(media=media), 200


@media_bp.route('/media/delete/<int:media_id>', methods=['POST'])
@auth.enabled_editor_required__json
def delete_media(media_id):
    media = Media.find(id=media_id, user_id=flask_login.current_user.id)
    if media:
        media.delete()
        if flask_login.current_user.set_disk_usage_alert():
            flask_login.current_user.save()
        total_usage = flask_login.current_user.total_uploads_usage()
        media_usage = flask_login.current_user.media_usage()
        percent = (total_usage * 100) / flask_login.current_user.uploads_limit
        percent = "{:.2f} %".format(percent)
        return jsonify(
            media_id=media.id,
            usage_percent=percent,
            total_usage=total_usage,
            media_human_usage=utils.human_readable_bytes(media_usage),
            total_human_usage=utils.human_readable_bytes(total_usage),
            show_alert=bool(flask_login.current_user.alerts)
        ), 200
    return jsonify(False), 404


@media_bp.route('/media/get-values/<int:media_id>', methods=['GET'])
@auth.enabled_user_required__json
def get_values(media_id):
    media = Media.find(id=media_id, user_id=flask_login.current_user.id)
    if media:
        return jsonify(media=MediaSchema().dump(media)), 200
    return jsonify(False), 404

liberaforms/views/user.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2020 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

import os
from flask import g, request, render_template, redirect
from flask import Blueprint, current_app, url_for
from flask import flash, jsonify
from flask_babel import gettext as _
from flask_babel import refresh as babel_refresh
import flask_login
from liberaforms.models.user import User
from liberaforms.models.consent import Consent
from liberaforms.models.schemas.consent import ConsentSchema
from liberaforms.domain.user import UserDomain
from liberaforms.utils.dispatcher import Dispatcher
from liberaforms.utils import utils
from liberaforms.utils import validators
from liberaforms.utils import password as password_utils
from liberaforms.utils import auth
from liberaforms.utils import tokens
from liberaforms.utils import wtf
from liberaforms.utils import chart_data

#from pprint import pprint

user_bp = Blueprint('user_bp',
                    __name__,
                    template_folder='../templates/user')


@user_bp.route('/user/new', methods=['GET', 'POST'])
@user_bp.route('/user/new/<string:invite>', methods=['GET', 'POST'])
@tokens.instantiate_invite
def create_new_user(invite=None):
    if g.site.invitation_only and not invite:
        return redirect(url_for('main_bp.index'))
    flask_login.logout_user()
    if invite and invite.has_ldap_entry():
        return redirect(url_for('user_bp.login', invite=invite.token['token']))
    wtform = wtf.NewUser()
    consents = g.site.get_registration_consents()
    if wtform.validate_on_submit() and Consent.validate(request.form, consents):
        validated_email = False
        send_admin_notification = True
        role = 'editor'  # default role
        if invite:
            role = invite.role
            if invite.email == wtform.email.data:
                validated_email = True
                if wtform.email.data == current_app.config['ROOT_USER']:
                    # SMTP has not been configured yet
                    send_admin_notification = False
        elif wtform.email.data == current_app.config['ROOT_USER']:
            flash(_("Invitation only"), 'error')
            wtform.email.data = ""
            return render_template('new-user.html',
                                   consents=ConsentSchema(many=True).dump(consents),
                                   wtform=wtform)
        try:
            new_user = User(
                username=wtform.username.data,
                email=wtform.email.data,
                password=wtform.password.data,
                role=role,
                invited_by_id=invite.invited_by_id if invite else None,
                validated_email=validated_email,
            )
            new_user.save()
        except Exception as error:
            current_app.logger.error(error)
            flash(_("Opps! An error ocurred when creating the user"), 'error')
            return render_template('new-user.html')
        if invite:
            if invite.granted_form:
                domain = UserDomain(new_user.username, wtform.password.data)
                domain.grant_form_answers(invite)
            invite.delete()
        if not new_user.validated_email:
            new_user.save_token(email=new_user.email)
            Dispatcher().send_email_address_confirmation(new_user, new_user.email)
        if send_admin_notification:
            Dispatcher().send_new_user_notification(new_user)
        current_app.logger.info(f'USER - New user "{new_user.username}" with role "{new_user.role}" created.')
        flask_login.login_user(new_user)
        current_app.logger.info(f'USER - "{new_user.username}" logged in')
        babel_refresh()
        flash(_("Welcome!"), 'success')
        return redirect(url_for('user_bp.user_settings',
                                username=flask_login.current_user.username))
    flask_login.logout_user()
    if not wtform.email.data and invite:
        wtform.email.data = invite.email
    return render_template('new-user.html',
                           consents=ConsentSchema(many=True).dump(consents),
                           wtform=wtform)


@user_bp.route('/user/validate-to-continue', methods=['GET', 'POST'])
@auth.unvalidated_user_required
def validate_to_continue():
    wtform = wtf.NewEmailAddress()
    if wtform.validate_on_submit():
        flask_login.current_user.save_token(email=wtform.email.data)
        status = Dispatcher().send_email_address_confirmation(flask_login.current_user,
                                                              wtform.email.data)
        if status['email_sent'] is True:
            flash(_("We have sent an email to %(email)s", email=wtform.email.data), 'info')
        else:
            flash(status['msg'], 'warning')
            current_app.logger.warning(status['msg'])
    if request.method == 'GET':
        wtform.email.data = flask_login.current_user.email
    delete_account_link = utils.build_link(_("Changed your mind? You may $$delete your account here$$"),
                                           url_for('user_bp.delete_account'),
                                           _class="link-danger")
    return render_template('unvalidated/validate-email.html',
                           wtform=wtform,
                           delete_account_link=delete_account_link)


@user_bp.route('/user/validate-email/<string:token>', methods=['GET'])
@tokens.sanitized_token
def validate_email(token):
    """Use to validate an email."""
    user = User.find(token=token)
    if not user:
        flash(_("We couldn't find that petition"), 'warning')
        if flask_login.current_user.is_authenticated:
            return redirect(url_for('user_bp.user_settings',
                            username=flask_login.current_user.username))
        return redirect(url_for('main_bp.index'))
    if tokens.has_token_expired(user.token):
        flash(_("Your petition has expired"), 'warning')
        user.delete_token()
        if flask_login.current_user.is_authenticated:
            return redirect(url_for('user_bp.user_settings',
                            username=flask_login.current_user.username))
        return redirect(url_for('main_bp.index'))
    if 'email' in user.token:
        user.email = user.token['email']
        is_new_user = not user.validated_email
        if is_new_user:
            current_app.logger.info(f'USER - New user "{user.username}" validated email {user.email}')
            flash(_("Welcome!"), 'success')
        else:
            flash(_("Your new email is valid"), 'success')
        user.validated_email = True
        user.save()
    user.delete_token()
    flask_login.login_user(user)
    return redirect(url_for('user_bp.user_settings', username=user.username))

# ## Personal user settings


@user_bp.route('/user', methods=['GET'])
@user_bp.route('/user/<string:username>', methods=['GET'])
@flask_login.login_required
@auth.enabled_user_required
def user_settings(username=None):
    """Render the User settings page."""
    if username and username != flask_login.current_user.username:
        return redirect(url_for('user_bp.user_settings',
                                username=flask_login.current_user.username))
    if flask_login.current_user.update_alerts():
        flask_login.current_user.save()
    return render_template('user-settings.html',
                           human_readable_bytes=utils.human_readable_bytes)


@user_bp.route('/user/change-language', methods=['GET', 'POST'])
@auth.enabled_user_required
def change_language():
    if request.method == 'POST':
        if 'language' in request.form and \
           request.form['language'] in current_app.config['LANGUAGES']:
            flask_login.current_user.preferences["language"] = request.form['language']
            flask_login.current_user.save()
            babel_refresh()
            return redirect(url_for('user_bp.user_settings',
                            username=flask_login.current_user.username))
    current_language = flask_login.current_user.preferences["language"]
    return render_template('change-language.html', current_language=current_language)


@user_bp.route('/user/statistics', methods=['GET'])
@auth.enabled_user_required
def statistics():
    return render_template('user/statistics.html',
                           stats=chart_data.get_user_statistics(flask_login.current_user))


@user_bp.route('/user/statistics/year', methods=['GET'])
@auth.enabled_user_required__json
def get_user_usage_graph_data():
    try:
        offset = int(request.args.get("year-offset", 0))
        return jsonify(chart_data=chart_data.get_user_statistics(flask_login.current_user,
                                                                 offset_year=offset))
    except:
        current_app.logger.debug("APP - Failed to get user usage graph data")
        return jsonify("Not acceptable"), 406


@user_bp.route('/user/change-email', methods=['GET', 'POST'])
@auth.enabled_user_required
def change_email():
    wtform = wtf.NewEmailAddress()
    if wtform.validate_on_submit():
        flask_login.current_user.save_token(email=wtform.email.data)
        status = Dispatcher().send_email_address_confirmation(flask_login.current_user,
                                                              wtform.email.data)
        if status['email_sent'] is True:
            flash(_("We have sent an email to %(email)s", email=wtform.email.data), 'info')
        else:
            # TODO: Tell the user that the email has not been sent
            pass
        return redirect(url_for('user_bp.user_settings',
                                username=flask_login.current_user.username))
    return render_template('change-email.html', wtform=wtform)


@user_bp.route('/user/recover-password/<string:token>', methods=['GET'])
@auth.anonymous_user_required
@tokens.sanitized_token
def recover_password(token=None):
    if token:

liberaforms/templates/user/statistics.html
{% extends "base-backend.html" %}
{% block content %}

<script src="{{ url_for('static', filename='vendor/chartjs/3.6.2/chart.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/chartjs/3.6.2/chartjs-adapter-date-fns.bundle.min.js') }}"></script>

<div class="grid ds-header-title">
  <div class="g-col-12">
    <h1>{{ _("My statistics") }}</h1>
  </div>
</div>

<div class="grid mt-3">
  <div class="g-col-12">
    <p class="mb-0">{{ _("Statistics corresponding to the last twelve months of all your forms and answers.") }}</p>
  </div>
</div>

<div class="grid mt-3">
  <div class="g-col-12">
    <div class="card">
      <div class="card-header">
        <h2>
          {{ _("Statistics") }}
          <a href="javascript:void(0)" onclick="javascript:changeYear(-1)"><i data-feather="chevron-left" width="16" height="16" stroke-width="3" aria-label="Previous year"></i></a>
          <span id="stats_year_end">{{stats['year_end']}}</span>
          <a href="javascript:void(0)" onclick="javascript:changeYear(+1)"><i data-feather="chevron-right" width="16" height="16" stroke-width="3" aria-label="Next year"></i></a>
        </h2>
      </div>
      <div class="card-body ds-card-body-with-chart">
        <canvas id="usage-chart" height=100></canvas>
      </div>
    </div>
  </div>
</div>


<script>
const inline_help_file_name = "user_statistics.j2.md";
var data_cache = { 0: {{stats|tojson}} }
var legend_status = [0, 1]
var current_year = 0;

function getDataSets(stats) {
  return [
      {
          label: ["{{ _('Answers')}}"],
          data: stats.answers,
          hidden: !legend_status.includes(0),
          backgroundColor: "rgba(182, 0, 181, 0.7)",
      },
      {
          label: ["{{ _('Total answers')}}"],
          data: stats.total_answers,
          hidden: !legend_status.includes(1),
          backgroundColor: "rgba(0, 190, 0, 0.7)",
      },
      {
          label: ["{{ _('New forms')}}"],
          data: stats.forms,
          hidden: !legend_status.includes(2),
          backgroundColor: "rgba(233, 132, 0, 0.7)",
      },
      {
          label: ["{{ _('Total forms')}}"],
          data: stats.total_forms,
          hidden: !legend_status.includes(3),
          backgroundColor: "rgba(255, 228, 0, 0.7)",
      },
  ]
}

const usage_chart = new Chart(document.getElementById('usage-chart'), {
    type: 'bar',
    data: {
        labels:  {{ stats['labels']|tojson }},
        beginAtZero: true,
        datasets: getDataSets({{ stats|tojson }}),
    },
    options: {
      responsive: true,
      maintainAspectRatio: true,
      scales: {
          y: {
            beginAtZero: true,
            ticks: { precision: 0 }
          }
      },
      plugins: {
        legend: {
          onHover: function (e) {
            e.native.target.style.cursor = 'pointer';
          },
          onLeave: function (e) {
            e.native.target.style.cursor = 'default';
          },
          onClick: function (e, legend_item) {
            if (legend_status.includes(legend_item.datasetIndex)) {
              let pos = legend_status.indexOf(legend_item.datasetIndex);
              legend_status.splice(pos, 1);
            } else {
              legend_status.push(legend_item.datasetIndex)
            }
            Chart.defaults.plugins.legend.onClick.call(null, null, legend_item, e);
          },
          labels: {
            boxWidth: 20,
            usePointStyle: true,
            pointStyle: "rectRounded",
          }
        },
      },
      animation: {
        duration: 500,
      },
    },
});
function updateChart() {
  data = data_cache[current_year]
  $("#stats_year_end").html(data.year_end)
  usage_chart.data.labels = data.labels;
  usage_chart.data.datasets = getDataSets(data);
  usage_chart.update();
}
function changeYear(increment) {
  current_year = current_year + increment
  if (current_year > 0) {
    current_year = 0
    return
  }
  if (data_cache[current_year] !== undefined) {
    updateChart()
    return
  }
  $.ajax({
    url : "{{url_for('user_bp.get_user_usage_graph_data')}}"+"?year-offset="+current_year,
    type: "GET",
    dataType: "json",
    beforeSend: function(xhr, settings) {
      if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    },
    success: function(data, textStatus, jqXHR)
    {
      data_cache[current_year] = data.chart_data
      updateChart()
    }
  });
}
</script>

{% endblock %}

liberaforms/templates/user/user-settings.html
{% extends "base-backend.html" %}
{% block content %}

<!-- user_settings_page -->

<div class="ds-narrow-container">
  <div class="grid ds-header-title">
    <div class="g-col-12">
      <h1>{{ _("Hello %(username)s!", username=current_user.username) }}</h1>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <p class="mb-0">{{ _("Your account configuration.") }}</p>
    </div>
  </div>

  <div class="grid mt-3">
    <div class="g-col-12">
      <div class="card">
        <div class="card-header">
          <h2>{{ _("General") }}</h2>
        </div>
        <div class="card-body">
          <ul class="ds-list-group">
            {% if not (config['ENABLE_LDAP'] and current_user.ldap_uuid) %}
            <li>
              <span>{{ _("Email") }}: <strong>{{ current_user.email }}</strong></span>
              <a class="ds-link-contain-icon" href="{{url_for('user_bp.change_email')}}">{{ _("Change") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
            <li>
              <span>{{ _("Password") }}</span>
              <a class="ds-link-contain-icon" href="{{url_for('user_bp.reset_password')}}">{{ _("Change") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
            {% endif %}
            <li>
              <span>{{ _("Avatar") }}</span>
              <a class="ds-link-contain-icon" href="{{url_for('user_bp.set_avatar')}}">{{ _("Change") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
            <li>
              <span>{{ _("Language") }}: <strong>{{ config['LANGUAGES'][current_user.get_language()][0] }}</strong></span>
              <a class="ds-link-contain-icon" href="{{url_for('user_bp.change_language')}}">{{ _("Change") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
            <li>
              <span>{{ _("Time zone") }}: <strong>{{ current_user.get_timezone() }}</strong></span>
              <a class="ds-link-contain-icon" href="{{url_for('user_bp.change_timezone')}}">{{ _("Change") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
            <li>
              <span class="text-danger"><strong>{{ _("Delete my account") }}</strong></span>
              <a class="ds-link-contain-icon link-danger" href="{{url_for('user_bp.delete_account')}}">{{ _("Delete") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  {% if current_user.is_active() and current_user.is_editor() %}
  <div class="grid mt-4">
    <div class="g-col-12">
      <div class="card">
        <div class="card-header">
          <h2>{{ _("Form notifications") }}</h2>
        </div>
        <div class="card-body">
          <ul class="ds-list-group">
            <li>
              <span>{{ _("Notify me on each new answer") }}</span>
              <div id="toggle_new_answer_notification" class="btn-group btn-toggle">
                {% set new_answer_notification = current_user.new_answer_notification_default() %}
                <button id="new_answer_notification_true" class="btn btn-sm {% if new_answer_notification %} btn-primary {% else %} btn-outline-secondary {% endif %}">{{ _("True") }}</button>
                <button id="new_answer_notification_false" class="btn btn-sm {% if not new_answer_notification %} btn-primary {% else %} btn-outline-secondary {% endif %}">{{ _("False") }}</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% if current_user.is_active() and current_user.is_editor() %}
  {% if current_user.uploads_enabled and config['CRYPTO_KEY'] %}

  {% set media_usage = current_user.media_usage() %}
  {% set attachments_usage = current_user.attachments_usage() %}
  {% set total_usage = media_usage + attachments_usage %}
  <div class="grid mt-4">
    <div class="g-col-12">
      <div class="card">
        <div class="card-header">
          <h2>{{ _("Disk usage") }}</h2>
        </div>
        <div class="card-body">
          <ul class="ds-list-group">
            <li>
              <span>
                {{ _("Total used") }}
                <span class="badge rounded-pill {% if total_usage < current_user.uploads_limit %} text-bg-secondary {% else %} text-bg-warning {% endif %}">
                  {% if total_usage > 0 %}
                  {{'%0.2f' % (( total_usage * 100) / current_user.uploads_limit )|float}} %
                  {% else %}
                  0 %
                  {% endif %}
                </span>
              </span>
              <span>
                {{ _("%(total_used_bytes)s of %(assigned_bytes)s",
                      total_used_bytes = human_readable_bytes(total_usage),
                      assigned_bytes = human_readable_bytes(current_user.uploads_limit)
                      ) }}
              </span>
            </li>
            <li>
              <span>{{ _("Form attachments") }}</span>
              <span>{{ human_readable_bytes(attachments_usage) }}</span>
            </li>
            <li>
              <span>{# i18n: shows the total disk usage that user has made along all their forms, displayed in User settings #}{{ _("Form media") }}</span>
              <span>{{ human_readable_bytes(media_usage) }}</span>
            </li>
            <li>
              <span>{{ _("Add and delete form media") }}</span>
              <a class="ds-link-contain-icon" href="{{url_for('media_bp.list_user_media')}}">{{ _("Edit") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  {% endif %}

  {% if current_user.can_configure_fediverse() %}
  <div class="grid mt-4">
    <div class="g-col-12">
      <div class="card">
        <div class="card-header">
          <h2>
            {# i18n: means Digital social networks #}
            {{ _("Social media") }}
          </h2>
        </div>
        <div class="card-body">
          <ul class="ds-list-group">
            <li>
              <span>{{ _("Fediverse connect") }}
                {% if current_user.fedi_auth %}
                  <strong>{{ current_user.get_fedi_auth()['node_url'] }}</strong>
                {% endif %}
              </span>
              <a href="{{url_for('user_bp.fediverse_config')}}" class="ds-link-contain-icon">{{ _("Configure") }} <i data-feather="chevron-right" aria-hidden="true"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% if current_user.is_active() and current_user.is_admin() %}
  <div class="grid mt-4">
    <div class="g-col-12">
      <div class="card">
        <div class="card-header">
          <h2 id="admin_settings">{{ _("My admin settings") }}</h2>
        </div>
        <div class="card-body">
          <ul class="ds-list-group">
            <li>
              <span>{{ _("Notify me when new user has registered") }}</span>
              <div id="toggle_notify_newuser" class="btn-group btn-toggle">
                <button id="notify_newuser_true" class="btn btn-sm {% if current_user.admin['notifyNewUser'] %} btn-primary {% else %} btn-outline-secondary {% endif %}">{{ _("True") }}</button>
                <button id="notify_newuser_false" class="btn btn-sm {% if not current_user.admin['notifyNewUser'] %} btn-primary {% else %} btn-outline-secondary {% endif %}">{{ _("False") }}</button>
              </div>
            </li>
            <li>
              <span>{{ _("Notify me when new form has been created") }}</span>
              <div id="toggle_notify_newform" class="btn-group btn-toggle">
                <button id="notify_newform_true" class="btn btn-sm {% if current_user.admin['notifyNewForm'] %} btn-primary {% else %} btn-outline-secondary {% endif %}">{{ _("True") }}</button>
                <button id="notify_newform_false" class="btn btn-sm {% if not current_user.admin['notifyNewForm'] %} btn-primary {% else %} btn-outline-secondary {% endif %}"> {{ _("False") }} </button>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% set contact_info = g.site.get_contact_info() %}
  {% if contact_info %}
  <div class="grid mt-4">
    <div class="g-col-12">
      <div class="card">
        <div class="card-header">
          <h2>{{ _("Other information") }}</h2>
        </div>
        <div class="card-body">
          {{ contact_info | safe }}
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>

<script>
const inline_help_file_name = "user.j2.md";

{% if not current_user.is_guest() %}
document.getElementById('toggle_new_answer_notification').addEventListener('click', function(evt){
    $.ajax({
        url : "{{url_for('user_bp.toggle_new_answer_notification_default')}}",
        type: "POST",
        dataType: "json",
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
        },
        success: function(data, textStatus, jqXHR)
        {
            if (data.default == true) {
                $('#new_answer_notification_true').addClass('btn-primary')
                                                  .removeClass('btn-outline-secondary');
                $('#new_answer_notification_false').removeClass('btn-primary')
                                                   .addClass('btn-outline-secondary');
            }
            else if (data.default == false) {
                $('#new_answer_notification_true').removeClass('btn-primary')
                                                  .addClass('btn-outline-secondary');
                $('#new_answer_notification_false').addClass('btn-primary')
                                                   .removeClass('btn-outline-secondary');
            }
        }
    });
});
{% endif %}
{% if current_user.is_admin() %}
document.getElementById('toggle_notify_newuser').addEventListener('click', function(evt){
    $.ajax({
        url : "{{url_for('admin_bp.toggle_newuser_notification')}}",
        type: "POST",
        dataType: "json",
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
        },
        success: function(data, textStatus, jqXHR)
        {
            if (data.notify == true) {
                $('#notify_newuser_true').addClass('btn-primary')
                                         .removeClass('btn-outline-secondary');
                $('#notify_newuser_false').removeClass('btn-primary')
                                          .addClass('btn-outline-secondary');
            }
            else if (data.notify == false) {
                $('#notify_newuser_true').removeClass('btn-primary')
                                         .addClass('btn-outline-secondary');
                $('#notify_newuser_false').addClass('btn-primary')
                                          .removeClass('btn-outline-secondary');
            }
        }
    });
});
document.getElementById('toggle_notify_newform').addEventListener('click', function(evt){
    $.ajax({
        url : "{{url_for('admin_bp.toggle_newform_notification')}}",
        type: "POST",
        dataType: "json",
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
        },
        success: function(data, textStatus, jqXHR)
        {
            if (data.notify == true) {
                $('#notify_newform_true').addClass('btn-primary')
                                         .removeClass('btn-outline-secondary');
                $('#notify_newform_false').removeClass('btn-primary')
                                          .addClass('btn-outline-secondary');
            }
            else if (data.notify == false) {
                $('#notify_newform_true').removeClass('btn-primary')
                                         .addClass('btn-outline-secondary');
                $('#notify_newform_false').addClass('btn-primary')
                                          .removeClass('btn-outline-secondary');
            }
        }
    });
});
{% endif %}
</script>

{% endblock %}